### ISSUE TITLE
"reseed_counter" is poosibly not updated for CTR_DRBG

### ISSUE THREAD

**Issue by jimmy92120** [ANSSI-FR/libdrbg#3]
Hello,

This is based only on code reading:
In generate process for CTR DRBG, reseed counter updating seems not to be found.

Sorry if this is actually done...
Best Regards,

**Comment by rben-dev** [comment]
Hi!

Thanks for reporting this, the incrementation is indeed missing (it is a shame the NIST test vectors do not test this).
Anyways, this should be fixed in PR #4 

Regards,
